module mo_ui._parser{
    export interface UIKey{
        className:string;
        designHeight:string;
        designWidth:string;
        textures:string;
        widgetTree:string;
        dataScale:string;
        name:string;
        actionTag:string;
        x:string;
        y:string;
        width:string;
        height:string;
        anchorX:string;
        anchorY:string;
        ignoreSize:string;
        posType:string;
        posPercentX:string;
        posPercentY:string;
        sizeType:string;
        sizePercentX:string;
        sizePercentY:string;
        tag:string;
        zOrder:string;
        children:string;
        colorType:string;
        color:string;
        customProperty:string;
        flipX:string;
        flipY:string;
        opacity:string;
        rotation:string;
        scaleX:string;
        scaleY:string;
        touchEnabled:string;
        useMergedTexture:string;
        visible:string;
        fontName:string;
        fontSize:string;
        text:string;
        textColor:string;
        areaHeight:string;
        areaWidth:string;
        hAlignment:string;
        vAlignment:string;
        itemWidth:string;
        itemHeight:string;
        startCharMap:string;
        touchScaleEnable:string;
        layoutParameter:string;
        adaptScreen:string;
        bg:string;
        bgData:string;
        bgColor:string;
        bgOpacity:string;
        bgStartColor:string;
        bgEndColor:string;
        scale9Grid:string;
        scale9Enabled:string;
        clippingEnabled:string;
        layoutType:string;
        vectorX:string;
        vectorY:string;
        fileName:string;
        fileNameData:string;
        scaleWidth:string;
        scaleHeight:string;
        maxLengthEnable:string;
        passwordEnable:string;
        passwordStyleText:string;
        placeHolder:string;
        direction:string;
        percent:string;
        innerWidth:string;
        innerHeight:string;
        gravity:string;
        itemMargin:string;

        normal:string;
        pressed:string;
        disabled:string;

        type:string;
        align:string;
        eageType:string;
        normalHorizontal:string;
        normalVertical:string;
        parentHorizontal:string;
        parentVertical:string;
        margin:string;

        //mo拓展
        res:string;
        uiText:string;
    }

    var normalKey:UIKey = {
        className:"className",
        designHeight:"designHeight",
        designWidth:"designWidth",
        textures:"textures",
        widgetTree:"widgetTree",
        dataScale:"dataScale",
        name:"name",
        actionTag:"actionTag",
        x:"x",
        y:"y",
        width:"width",
        height:"height",
        anchorX:"anchorX",
        anchorY:"anchorY",
        ignoreSize:"ignoreSize",
        posType:"posType",
        posPercentX:"posPercentX",
        posPercentY:"posPercentY",
        sizeType:"sizeType",
        sizePercentX:"sizePercentX",
        sizePercentY:"sizePercentY",
        tag:"tag",
        zOrder:"zOrder",
        children:"children",
        colorType:"colorType",
        color:"color",
        customProperty:"customProperty",
        flipX:"flipX",
        flipY:"flipY",
        opacity:"opacity",
        rotation:"rotation",
        scaleX:"scaleX",
        scaleY:"scaleY",
        touchEnabled:"touchEnabled",
        useMergedTexture:"useMergedTexture",
        visible:"visible",
        fontName:"fontName",
        fontSize:"fontSize",
        text:"text",
        textColor:"textColor",
        itemWidth:"itemWidth",
        itemHeight:"itemHeight",
        startCharMap:"startCharMap",
        areaHeight:"areaHeight",
        areaWidth:"areaWidth",
        hAlignment:"hAlignment",
        vAlignment:"vAlignment",
        touchScaleEnable:"touchScaleEnable",
        layoutParameter:"layoutParameter",
        adaptScreen:"adaptScreen",
        bg:"_bg",
        bgData:"bgData",
        bgColor:"bgColor",
        bgOpacity:"bgOpacity",
        bgStartColor:"bgStartColor",
        bgEndColor:"bgEndColor",
        scale9Grid:"scale9Grid",
        scale9Enabled:"scale9Enabled",
        clippingEnabled:"clippingEnabled",
        layoutType:"layoutType",
        vectorX:"vectorX",
        vectorY:"vectorY",
        fileName:"fileName",
        fileNameData:"fileNameData",
        scaleWidth:"scaleWidth",
        scaleHeight:"scaleHeight",
        maxLengthEnable:"maxLengthEnable",
        passwordEnable:"passwordEnable",
        passwordStyleText:"passwordStyleText",
        placeHolder:"placeHolder",
        direction:"direction",
        percent:"percent",
        innerWidth:"innerWidth",
        innerHeight:"innerHeight",
        gravity:"gravity",
        itemMargin:"itemMargin",

        normal:"normal",
        pressed:"pressed",
        disabled:"disabled",

        type:"type",

        align:"align",
        eageType:"eageType",
        normalHorizontal:"normalHorizontal",
        normalVertical:"normalVertical",
        parentHorizontal:"parentHorizontal",
        parentVertical:"parentVertical",
        margin:"margin",

        //mo拓展
        res:"res",
        uiText:"uiText"
    };
    export function getUIKey(uglified:boolean = false){
        return normalKey;
    }
}