module mo{
    export class Ease extends egret.Ease{
        //get
        //getPowIn
        //getPowOut
        //getPowInOut
        //quadIn
        //quadOut
        //quadInOut
        //cubicIn
        //cubicOut
        //cubicInOut
        //quartIn
        //quartOut
        //quartInOut
        //quintIn
        //quintOut
        //quintInOut
        //sineIn
        //sineOut
        //sineInOut
        //getBackIn
        //backIn
        //getBackOut
        //backOut
        //getBackInOut
        //backInOut
        //circIn
        //circOut
        //circInOut
        //bounceIn
        //bounceOut
        //bounceInOut
        //getElasticIn
        //getElasticOut
        //elasticOut
        //getElasticInOut
        //elasticInOut
    }
}